### ISSUE TITLE
WhileyCompiler in win32 x86

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [Whiley/WhileyCompiler#1015]
Hello, everyone!
How to install and build and run WhileyCompiler in Windows 7 32bit x86?
Thanks

**Comment by MortezaRahmaniJRP** [comment]
It should be noted that I compiled HelloWorld program in hello.whiley file to hello.wyil and hello.wyal both,but I have a problem in running:

`WARNING: version numbering unavailable
usage: run <wyilfile> <method>`
and files:
[http://uupload.ir/view/fboc_hello.zip/](url)
(please translate page to English or your custom language)

**Comment by DavePearce** [comment]
Hey Morteza,

Ok, I just need a bit more information.  There are basically three options:

1. Download one of the existing distributions from [here](https://github.com/Whiley/WhileyDevelopmentKit/tree/master/dist).  The latest one is a little out of date and I'm going to make a new release soon.
2. Clone the  [WhileyDevelopmentKit](https://github.com/Whiley/WhileyDevelopmentKit) repository and the run `ant dist`.  This should create a directory `dist/wdk-0.5.0` containing the latest versions of all components.  If you set the environment `WHILEYHOME` to point to this directory then you should be able to run `wy` from the command line.
3. Rebuild from the source.  To do this, you will need to clone the [WhileyCompilerCollection](https://github.com/Whiley/WhileyCompilerCollection), the [WhileyCompiler](https://github.com/Whiley/WhileyCompiler) and I would also recommend the [Whiley2JavaScript](https://github.com/Whiley/Whiley2JavaScript).  In each repository you need to run `ant plugin` which will install the component into `WHILEYHOME/lib`.

Depending on what you're trying to do, I would say option (2) is a good way to start.  Note also that `wy run` doesn't do anything at the moment.  To get Whiley code executing you need to generate JavaScript.  You can see an example program [here](https://github.com/DavePearce/Minesweeper.wy).  Also, you can run Whiley in the webbrowser directly on [WhielyLabs](http://whileylabs.com).
