### ISSUE TITLE
Switch_Valid_3 test, failing on default case

### ISSUE THREAD

**Issue by Matt--** [Whiley/WhileyCompiler#368]
There doesn't appear to be a current issue open for this.

This test contains a default path. It appears the switch bytecode allocates a duplicate label0 to both the default and to an earlier case ("QUEEN").

When you examine the bytecode for the default, there is no label bytecode for the default case ("GOT NOTHING").

Bytecode for the switch statement;
switch %7 'N'->label1, 'B'->label2, 'R'->label3, 'Q'->label0, 'K'->label4, *->label0

Bytecode showing the missing label for the default case;
...
goto label5
.label4
const %14 = "GOT KING" : string
assign %8 = %14  : string
goto label5
const %15 = "GOT NOTHING" : string
assign %8 = %15  : string
goto label5
.label5
...

**Comment by DavePearce** [comment]
Looks ok now.
