### ISSUE TITLE
Ensures_Valid_6 - loop error

### ISSUE THREAD

**Issue by Matt--** [Whiley/WhileyCompiler#369]
The C code I am generating for this test is getting stuck in a loop in this tests abs() function.
The bytecode, reads;
```
...
  .label3
  assign %3 = %0  : int
  convert %3 = %3 null|int : int
  ifis %3, int goto label3 : null|int
...
```

I have been ignoring the convert bytecode for my compiler (which might be the problem?). 
My C version of the above, generating the loop, is;
```
...
  label3: ;
  Any a3 = a0;             // a0 is an INT_TYPE
  if(a3.type == INT_TYPE){ goto label3; };
...
```

Cheers

**Comment by DavePearce** [comment]
Doesn't seem to be a problem any more.
