### ISSUE TITLE
Syntax of negation/union, function return type

### ISSUE THREAD

**Issue by Matt--** [Whiley/WhileyCompiler#370]
For reference, test; NegationType_Valid_4

The function declaration is;
function f(string x) => !null | int:
Which I read as (!null) | int

The bytecode is;
return %1 : !(null | int)
Which is different. I suspect the function declaration needs brackets?

**Comment by DavePearce** [comment]
Yes, this still fails:

<pre>
function f(int[] x) -> !null | int:
    return 1
</pre>

Whilst this succeeds:

<pre>
function f(int[] x) -> ((!null) | int r):
    return 1
</pre>

**Comment by DavePearce** [comment]
Completed by @richdougherty
