### ISSUE TITLE
Test case FunctionRef_Valid_3

### ISSUE THREAD

**Issue by Matt--** [Whiley/WhileyCompiler#422]
A question on the return type and a bug as well in the test case. They may or may not be related...

<pre>
FunctionRef_Valid_3:

import whiley.lang.System

function f(int x) => int:
    return x * 12

function g(function(int)=>real func) => real:
    return func(1)

method main(System.Console sys) => void:
    sys.out.println(Any.toString(g(&f)))
</pre>

The question is that the sysout file gives the result as "12". I'm pretty sure it should be "12.0" as println is on the result of g which returns a real. I just wanted to check with you before I changed my copy of the sysout file.

The bug, is that function f's signature is function(int) => int but function g uses the parameter type function(int) => real.

Cheers
Matt

**Comment by DavePearce** [comment]
With the completion of #495, this is now resolved.
