### ISSUE TITLE
Remove Protected Modifier

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#448]
Although I ultimately want to support this modifier, it's currently not properley implemented. Therfore I should remove it and put together a proper feature request.
See #313

**Comment by sirinath** [comment]
I think modifiers are not needed if you look at a modifier as a contain. This way you can invent your own modifiers with required granularity.

**Comment by DavePearce** [comment]
Hi Suminda,

Sorry, I'm not really understanding what you mean here.  Ultimately, for the protected modifier to work correctly as I originally envisaged, it does need support within the compiler itself.  However, I would like to add a separate annotation mechanism, perhaps similar to that found in Java to allow lightweight modifiers to be given.

Cheers,

Dave

**Comment by sirinath** [comment]
Public, private, protected are not needed if you can have a modifier mechanism which can enforce certain access restriction and constraint.
