### ISSUE TITLE
Implementation for Print I/O

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#484]
The current mechanism for printing strings to I/O streams is far from ideal.  The mechanism currently is:
1. use <code>println</code> to print the standard string for any data value.  Note that <code>string</code> values are printed as integer lists, etc.
2. use <code>println_s</code> to print a <code>string</code> value as a true string.

This mechanism evolved as a result of the removal of the <code>string</code> data type.  Furthermore, it is heavily influenced by Java's approach, but is not memory efficient and is really a problem on embedded systems.

Therefore, what we ideally want is some kind of type-safe <code>printf</code> equivalent.  There are a few possible candidates:
- <code>print([string|Fmt])</code>.  Part from the nested list, this is quite nice.  Introduction of open tuples would potentially improve the signature.  Using it would be something like this: <code>print(["There are ",Fmt.Int(x)," items."])</code>.  The <code>Fmt</code> constructors could accept parameters to e.g. specify decimal places, etc.
- <code>print(string,[Fmt])</code>.  This is similar, but relies on embedded argument numbers in the format string.  Following Rust, this could be something like this: <code>print("There are {} items.",[Fmt.Int(x)])</code>.  The problem with this is that it's hard to make it type safe.  In principle, we could use verification for this purpose, but it definitely doesn't work at the moment.

At this stage, I need to think a little more.  However, the first option above is probably the best for now.  In principle, if I can improve the syntax a little that will help.

**Comment by DavePearce** [comment]
This is related to #471 in that the removal of list append shoudn't happen before we've figured out better string I/O.  That's because the use of append is currently critical to this.

**Comment by DavePearce** [comment]
The solution to this is actually pretty simple.  We define the following in module ASCII:

```
public type PrintWriter is {
    method print(int) -> PrintWriter,
    method print(ASCII.string) -> PrintWriter,
    method endl()
}
```

This then allows us to write things such as the following:

```
ASCII.PrintWriter p = ...
p.print("The number is: ").print(1).endl()
```

This is then somehow similar to the C++ `<<` operator.  Furthermore, in the future when we have traits, we can extent this interface to support any type implementing the `toString()` trait.

**Comment by bambinella** [comment]
> ASCII.PrintWriter p = ...
p.print("The number is: ").print(1).endl()

This is the classic way of chaining in OO-languages, but it leads to harder to read code. Better to have a separate operator for chaining.

Dart has the ".." operator so that you can turn:

element.property1("name")
element.property2("something")

Into:

element..property1("name")..property2("something")

But I would prefer some kind of arrow operator.

**Comment by DavePearce** [comment]
I don't quite understand the ".." --- isn't just a longer version of "."?

> But I would prefer some kind of arrow operator.

Hmmm, C++ has `<<` which is almost there.  But I agree that this:

```
p <- "The number is: " <- endl
```
Is quite neat.  But, I don't know how to support it from a syntax perspective.

**Comment by bambinella** [comment]
The ".." operator is quite simple, it is described in:

16.17.2 Cascaded Invocations
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf

I have mixed feelings about it, it can lead to a bit of confusion when the programmer makes a ".." or "." typo. So it probably is better to have something more visually distinct.

**Comment by DavePearce** [comment]
For now, have just added these functions to `std.io`:

```
// Print an integer to stdout
public native method print(int value)

// Print an ASCII string to stdout
public native method print(ascii.string value)

// Print an integer to stdout (with newline terminator)
public native method println(int value)

// Print an ASCII string to stdout (with newline terminator)
public native method println(ascii.string value)
```

That will do for now at least.
