### ISSUE TITLE
Problem Function References and Name Mangling

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#554]
The following test case was show by @utting to fail at runtime:

<pre>
import whiley.lang.*

type SizeGetter is function(Sized) -> int

type Sized is {
    int size,
    SizeGetter getSize,
    ...
    }

type MultiSized is {
    int size,
    int count,
    SizeGetter getSize,
    ...
    }

public function getSized(Sized s) -> int:
    return s.size

constant DATA is [
      {size:3, getSize: &getSized},
      {size:5, count:4, getSize: &getSized},  // TODO: use getMultiSized
      {size:7, getSize: &getSized}
    ]

method sum(Sized[] values) -> int:
    int i = 0
    int total = 0
    while i < |values|:
	Sized ob = values[i]
	SizeGetter sg = ob.getSize
	// int size = ob.size       // this works
	// int size = getSized(ob)  // this works
	int size = sg(ob)           // this gives a run-time type error
	total = total + size
	i = i + 1
    return total
    
method main(System.Console sys):
    sys.out.println(sum(DATA))
</pre>

The error message reported is:

<pre>
Exception in thread "main" java.lang.NoSuchMethodError: sum1.getSized$Z9bFaA$WE9FJD$D2Vm$VD$a1Vo$FE$9Y$ND$H2$x$cgz(Lwyjc/runtime/WyRecord;)Ljava/math/BigInteger;
	at sum1$0.call(Unknown Source)
	at sum1.sum$4AbFaA$0D5ZL13$n0FS$o5$lJ$B4$d0VT$J5$ZC(./sum1.whiley)
	at sum1.main$2Ab737oHF4$i2$o$7C$N2Vm$7E$T0$q$7B$R2Vn$s4$a1Vw$ND$c2Vm$ch2VW$sC$R2Vt$sC$N2Vm1(./sum1.whiley)
	at sum1.main(./sum1.whiley)
</pre>

In essence, this looks like a problem with name mangling...

**Comment by DavePearce** [comment]
So, if we display the mangles as generated by <code>Whiley2JavaBuilder.nameMangle()</code> we get this:

<pre>
GOT: function(sum1:Sized) -> int
MANGLE: getSized$Z9bFaA$WL13$n0FS$o5$lJ$B4$d0VT$J5$Zx
...
GOT: X<function({X getSize,int size,...}) -> int>
MANGLE: getSized$Z9bFaA$WE9FJD$D2Vm$VD$a1Vo$FE$9Y$ND$H2$x$cgz
...
</pre>

We can see clearly that it's not generated the same name mangles.  In fact, the interesting thing here is that the problem is arising because one type is "raw" and the other contains a "nominal".  Interesting...

**Comment by DavePearce** [comment]
**UPDATE:** so the first mangle is occurring at the definition site.

**Comment by DavePearce** [comment]
So, thinking about this there are two options:

1. **Make all declarations use raw types**.  This means we convert the function or method declaration types to raw at the point of constructing the Jvm method.

2. **Ensure Lambda's keep nominal types**.  This means we copy over the nominal type for a lambda from the function in question.

Seems like I prefer option (2) above because this retains as we generally prefer to retain as much nominal information as possible.  I suppose I should add a test case or two.

**Comment by DavePearce** [comment]
Have added test case <code>FunctionRef_Valid_10</code>, which operates on a linked list.  However, this does not illustrate the problem on the JVM, although it does on the WyIL intepreter.

**Comment by utting** [comment]
Options 1 and 2 are interesting tradeoffs.  I assume that raw type means base type, while nominal means the full subtype information.

Z uses option 1 for typechecking (it just checks base types), but one must still use the richer type for reasoning.

Keeping nominal types (full subtype information) might make it easier to support F-bounded quantification in the future, so that methods within subtypes can know that one of their inputs is the subtype rather than the supertype?  This would be one step closer to supporting OOP.

**Comment by DavePearce** [comment]
Hey Mark,

Yeah, raw type means that we extract all nominal type information just leaving the "base" type.  For example:

<pre>
type Point is { int x, int y }

function f(Point p) -> int:
    ...
</pre>

The nominal type of function <code>f</code> is <code>function(Point)->int</code>, where as its raw type would be <code>function({int x,int y})->int</code>.

Yes, effectively, I use option (1) for type checking.  Option (2) is retained for providing better debugging output, and also potentially to allow overloading of constrained types (though this is not really implemented yet).

**Comment by DavePearce** [comment]
The problem is an interesting one.  Essentially, when a <code>Constant.V_LAMBDA</code> is created it is supplied with the type of the function in question.  However, since <code>Constant</code> is a WyIL class it does not support <code>Nominal</code> types, only single instances of <code>Type</code>.   At this point, a choice is made which originally was to use <code>Nominal.raw()</code>.  

Later this single instance is turned back into an instance of <code>Nominal</code> with both positions populated from the single <code>Type</code> instance, and passed into <code>FlowTypeChecker.resolveAsFunctionOrMethod()</code> as part of the effort to type check a separate invocation.  Unfortunately, <code>resolveAsFunctionOrMethod()</code> expects the <code>rawType()</code> to have a proper raw type, otherwise it doesn't work.  Hence, changing the original choice to use <code>Nominal.nominal()</code> instead of <code>Nominal.raw()</code> still fails.

**Comment by DavePearce** [comment]
So, what are the options?  Here are some:

1) Reconstruct a <code>wyc.lang.Constant</code> hierarchy which shadows <code>wyil.lang.Constant</code>.  This can then include proper <code>Nominal</code> type information.

2) ?

That's it!

**Comment by DavePearce** [comment]
Other options include:

3) Update the way that Nominal versus Raw type information is managed in the front end.  This would mean moving away from maintaining both Nominal and Raw types alongside each other and, instead, recalculating the Raw types on demand.  The performance hit from this could be offset by using a caching scheme for example.

**Comment by DavePearce** [comment]
*it seems possible that there are other situations where the loss of nominal information could be a problem...*

Right, I'm not sure about this now.  Basically it requires there to be a difference between the nominal and raw type for a constant.  There aren't many situations where this could arise, since constants are generally by their very nature "raw" in some sense.  It's only Lambda's that seem to bring in a non-raw type.

**Comment by DavePearce** [comment]
So, of course, the solution presents itself! The easiest thing is to have a proxy object to interface between the front-end AST and the WyIL which holds both types. And, we already have such an object: Expr.ConstantAccess ...

**Comment by DavePearce** [comment]
Right, fixed.
