### ISSUE TITLE
wyjc -verify does not verify variable initialisations.

### ISSUE THREAD

**Issue by utting** [Whiley/WhileyCompiler#557]
The attached program (bug_nat.txt) verifies and runs, even though it assigns a negative number to a variable that has a positive-values-only type.  I think the verifier should report an error at the initialisation.
--------------------------
import whiley.lang.*
type pos is (int x) where x > 0

method main(System.Console sys):
    pos nn = -3
    sys.out.println(nn)
----------------------------
$ wyjc -verify bug_nat.whiley 
$ wyj bug_nat
-3
[bug_nat.txt](https://github.com/Whiley/WhileyCompiler/files/76949/bug_nat.txt)

**Comment by DavePearce** [comment]
Hey Mark,

Yeah, this is yet another known issue: #333 

It's a work in progress, and something I will get to when I finish with #538 (which is close)

Am going to close this now, as duplicate.

D
