### ISSUE TITLE
Whiley compiler based on Truffle/Graal

### ISSUE THREAD

**Issue by hastebrot** [Whiley/WhileyCompiler#559]
Hi David,

I wonder if an adaptation to the Truffle framework is an idea for consideration for future versions of this compiler. Truffle is a framework for writing self-optimising AST interpreters and uses the Graal dynamic compiler which will be included soon in early access versions of JDK9.

Maybe this also plays well together with the modularisation of some parts of the Whiley compiler (I saw the WyRL repository).

**Comment by DavePearce** [comment]
Hey,

Well, I know a little of Truffle and have seen a few talks on it. I think it would be a very interesting project to see how well the Whiley compiler can be mapped into Truffle.  But, I'll be honest and say that's not something I would consider doing myself in the near future.  Unfortunately, it's too risky for me and also doesn't fit with all my future goals (e.g. compiling to native architectures, JavaScript, etc).

But, if you're interested in trying it ... I'm happy to give advice, etc!

D
