### ISSUE TITLE
Travis builds are failing even though local build runs fine

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#592]
And travis nondeterministically fails only one some builds.

**Comment by SebastianS90** [comment]
ignoring `Byte_Valid_3` and `Byte_Valid_4` seams to avoid travis failures. Maybe the tests are just too big and should be split up in 2 separate files each?

**Comment by DavePearce** [comment]
yeah, it's probably something to do with that.  We could split them up 
to improve reliability ...

On 19/02/16 23:48, SebastianS90 wrote:
> ignoring |Byte_Valid_3| and |Byte_Valid_4| seams to avoid travis
> failures. Maybe the tests are just too big and should be split up in 2
> separate files each?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Whiley/WhileyCompiler/issues/592#issuecomment-186168665>.
>

-- 
Senior Lecturer in Computer Science,
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

Office: Cotton 231
Telephone: +64 (0)4 463 5833
URL: http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
Closing because replaced by #601
