### ISSUE TITLE
wrong index in code.java?

### ISSUE THREAD

**Issue by he2he** [Whiley/WhileyCompiler#597]
In https://github.com/Whiley/WhileyCompiler/blob/master/modules/wyil/src/wyil/lang/Code.java#L281 it says `targets[0]`. I guess it's supposed to be `targets[i]`.

**Comment by DavePearce** [comment]
Indeed, that looks like a bug to me!

**Comment by DavePearce** [comment]
Ok, finally fixed this and should be in the next release <code>v0.3.39</code>
