### ISSUE TITLE
Update of dereferenced pointer is again broken in v0.3.39

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#602]
Related to #551 

Consider again this program:
````
method m(&int x):
    *x = 1
````

It worked fine with the `wyjc-all-v0.3.38.jar` release, but the latest `v0.3.39` release yields the error message we had before:
````
$ cat test.whiley 
method m(&int x):
    *x = 1
$ java -jar wyjc-all-v0.3.39.jar test.whiley 
./test.whiley:2: internal failure, Invalid type for Update
    *x = 1
    ^^
````

**Comment by DavePearce** [comment]
Hey,  yeah I have seen that.  I think it's something to do with the WyJC backend.  Am currently working on it as part of my branch <code>feature/474-blocks</code>.

**Comment by DavePearce** [comment]
Right, this is now fixed in the latest <code>develop</code> snapshot.
