### ISSUE TITLE
Handling of non-ASCII characters for numbers and identifiers

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#603]
Thanks to the [reviewers](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/573/add-a-lexer-for-the-whiley-programming/activity#comment-16002900) that checked my Pygments lexer for Whiley I can report the following issue:

In [`WhileyFileLexer.java`](https://github.com/Whiley/WhileyCompiler/blob/v0.3.39/modules/wyc/src/wyc/io/WhileyFileLexer.java) we use [`Character#isDigit(char)`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isDigit%28char%29) and [`Character#isLetter(char)`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isLetter%28char%29) where the Whiley Language Specification allows `[0-9]` respectively `[a-zA-Z]`. As a result of this, a Whiley program can contain numbers that consist of foreign symbols, e.g. `١+ ۲+ ३` is a well-formed expression that evaluates to `6`, because the the parser uses `BigInteger`'s constructor to do the transformation from `String` to a number. Even if it works fine, these numbers are a bit weird.

Furthermore, identifiers are allowed to contain any letters that are accepted by Javas `isLetter` method. This includes a lot of non-ASCII letters. It appears to work fine, but it is not consistent to the language specification and could cause unforeseen problems in intermediate representations if we expect them to be fully ASCII encodable.

**Comment by DavePearce** [comment]
Done
