### ISSUE TITLE
Do we want to have functions as subtypes of methods?

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#611]
Would there be any problem with `function(...)->(...)` being a subtype of `method(...)->(...)` if parameters have the same types?

```
type mymethod is method()->int

function f():
    mymethod m1 = &(->42) // doesn't work, as it is a function
    mymethod m2 = &(->*(new 42)) // works, as it is a method
```

**Comment by DavePearce** [comment]
Hey Sebastian,

Hmmm, not sure.  My hunch is that it is OK, but we'd need to think about it to be sure.

D

**Comment by DavePearce** [comment]
Done.
