### ISSUE TITLE
WyIL to WyVC transformation broken if local variables start with an underscore

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#615]
I want to change the files shipping as runtime, to rename all local variables or parameters that currently are named `this` to something else. Let's say the new name should be `_this`.
It won't work with the Stack: `compile-wyrt` aborts with an exception.

To reproduce it:
````bash
cd modules/wyrt
perl -i -pe 's/this/_this/g' src/whiley/lang/Stack.whiley 
ant build
````
You will get:
````
BUILD FAILED
~/WhileyCompiler/modules/wyrt/build.xml:6: wycc.lang.SyntaxError: expected type [any], got type int
````

If you capture the wyal file during the build and inspect it before and after doing the renaming, you'll see the following diff (that's only a short extract, but enough to illustrate the problem)
````diff
 assert "index out of bounds (not less than length)":
-    forall (whiley.lang.Stack.Stack this):
+    forall (int _this):
         if:
             true
         then:
-            this[1] < |this[0]|
+            _this[1] < |_this[0]|
````
Pretty surprising that the type changed, isn't it? And it explains our error message.

After hunting underscores in the source I found this little hack [here](https://github.com/Whiley/WhileyCompiler/blob/9a9b0702e23b181a92a8642b5fb5f935ec776806/modules/wyil/src/wyil/builders/VcGenerator.java#L1432):
````java
if (var.startsWith("_")) {
	// FIXME: this is a hack to handle the fact that forall index
	// variables are not explicit. However, we know that they are
	// always integers.
	type = Type.T_INT;
} else if (var.startsWith("null$")) {
	// FIXME: this is also something of a hack to deal with
	// expressions which currently have no sensible translation into
	// WyAL.
	type = Type.T_ANY;
} else {
	int reg = VcUtils.determineRegister(var, branch.prefixes());
	type = environment[reg];
}
````

It's probably not the best idea to assume that all variables starting with an underscore are `int`.
To resolve that bug we could rename all local variables that start with underscores. The dollar symbol might be handy for that.

**Comment by DavePearce** [comment]
Hey, 

That's a known feature of the Verification Condition Generator.  That code is a mess for various reasons, and it's actually hard to fix. See #501 and #538 for example, and the branch <code>feature/538-vcg</code> where I spent sometime trying to fix it and failed.

I believe I have figured out finally how to fix this problem, but it will take a while to get through the various bits of refactoring required to get to it.  See #563 as I'm working on it.

For now, just don't replace <code>this</code> with <code>_this</code>.  Use something like <code>it</code>, <code>me</code>, <code>thus</code> or just <code>t</code>.
