### ISSUE TITLE
Broken test cases in develop

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#622]
Some test cases are [broken](https://travis-ci.org/Whiley/WhileyCompiler/builds/123840605) in current develop:

* `DefiniteAssign_Invalid_4` has the wrong output
* `AddressExpression_Valid_2` does not compile with verification

**Comment by DavePearce** [comment]
Yeah, I know about these.  Not sure what's up with <code>AddressExpression_Valid_2</code>, but am going to look at them before merging to master.

**Comment by DavePearce** [comment]
Ok, <code>DefiniteAssign_Invalid_4</code> is fixed now.

**Comment by DavePearce** [comment]
Should be fixed now.
