### ISSUE TITLE
Question: Declaration by naming return value

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#623]
There was a change in Whiley where I am not sure whether it was on purpose.

We can name return values to use them inside `ensures` clauses. These names previously did not declare a variable for usage inside of the function body. Compare the following two programs:

old:

```
function fourtytwo() -> (int result)
ensures result == 42:
    int result = 42
    return result
```

new:

```
function fourtytwo() -> (int result)
ensures result == 42:
    result = 42 // note the missing "int"
    return result
```

The old program compiles on version v0.3.36 (try it on whiley.org/play/ which currently uses an old version).
The new program compiles on version v0.3.38 and newer. I didn't find a git tag for v0.3.37, so I couldn't test it with that version.

Compiling the old program on new versions yields "variable already declared". The other way around you get "unknown variable".

Was that change on purpose?

**Comment by DavePearce** [comment]
Hey,

So, yeah I was aware of that change.  To be honest, I think it's the right thing to do, as this is confusing:

<pre>
function f() -> (int r):
  int r = 0
  return 1
</pre>

I am happy with assignments to the return value within the function/method body.  In principle, I might even consider supporting something like this:

<pre>
function f() -> (int r):
  r = 0
  return
</pre>

So, here the return value is indicated by assignment rather than through the <code>return</code> statement.  I don't particularly like this, but I suppose it makes sense.

Thoughts?

**Comment by SebastianS90** [comment]
It's totally fine when it is on purpose :)

This here should be fixed:
````
function foo()->(int r)
requires r >= 0:
    return 1
````
Compiles fine without verification and yields an internal failure with verification. Should always yield something like unknown variable.


Allowing return by assignment sounds like a useful feature. But I don't know what to think about the following program:
````
function foo()->(int r):
    r = 1
    return 2
````

You could not only allow a plain `return` without value but also omitting the return statement. Then we could write:
````
function greaterTen(int x)->(bool r):
    if (x > 10):
        r = true
        return
    r = false
````

**Comment by DavePearce** [comment]
Hey,

So, yeah, it's interesting to think about it.  Your program is roughly equivalent to this:

<pre>
function foo()->(int r):
    r = 1
    return 2
</pre>

In some programming languages, assignment was the only way to indicate a return value.  Pascal is one example I think.  See here:

https://en.wikibooks.org/wiki/Pascal_Programming/Syntax_and_functions

**Comment by DavePearce** [comment]
Interesting to note the following program does compile:

```
function foo()->(int r):
    r = 1
    return r
```

But, at the same time, this program does not compile:

```
function foo()->(int r):
    r = 1
    return
```

Realistically, I think either both should compile or both should not compile! This could be turned into an RFC.

**Comment by DavePearce** [comment]
Ok, have created an RFC for this here: https://github.com/Whiley/RFCs/pull/16
