### ISSUE TITLE
Verifier cannot handle simple modulo mathematics

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#627]
I wanted to declare an even type, but couldn't get it working. The problem boils down to the following:
````
import whiley.lang.System

method main(System.Console console):
    assert 2 % 2 == 0
    console.out.println(2 % 2)
````
Compiles without verification. Runs and prints 0.
But it does not compile with verification:
````
Parsed 1 source file(s). ....................................................... [28ms+1mb]
Typed 1 source file(s). ........................................................ [82ms+2mb]
Generated code for 1 source file(s). ................................................ [9ms]
[./test.whiley] applied definite assignment check ................................... [1ms]
[./test.whiley] applied module check ................................................ [2ms]
[./test.whiley] applied loop variants ............................................... [0ms]
[./test.whiley] applied coercion check .............................................. [0ms]
Whiley => Wyil: compiled 1 file(s) ............................................ [197ms-5mb]
Wyil => Wyal: compiled 1 file(s) ............................................... [33ms+1mb]
Wyil => Java: compiled 1 file(s) ................................................... [23ms]
Parsed 1 source file(s). ............................................................ [0ms]
Generated stubs for 1 source file(s). .......................................... [75ms+2mb]
Typed 1 source file(s). ............................................................ [10ms]
Generated code for 1 source file(s). ................................................ [5ms]
[./test.whiley] applied macro expansion ............................................. [1ms]
[./test.whiley] Verified assertion #1 (steps: 1) .............................. [104ms+3mb]
[./test.whiley] failed on verification check (assertion failed) ............... [105ms+3mb]
./test.whiley:4: assertion failed
    assert 2 % 2 == 0
           ^^^^^^^^^^
wycc.lang.SyntaxError: assertion failed
	at wycc.lang.SyntaxError.syntaxError(SyntaxError.java:341)
	at wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:220)
	at wybs.util.StdBuildRule.apply(StdBuildRule.java:109)
	at wybs.util.StdProject.build(StdProject.java:256)
	at wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518)
	at wyc.util.WycBuildTask.build(WycBuildTask.java:486)
	at wyc.WycMain.run(WycMain.java:228)
	at wyjc.WyjcMain.main(WyjcMain.java:83)
Caused by: wycs.transforms.VerificationCheck$AssertionFailure: assertion failed
	at wycs.transforms.VerificationCheck.checkValid(VerificationCheck.java:220)
	at wycs.transforms.VerificationCheck.apply(VerificationCheck.java:164)
	at wycs.transforms.VerificationCheck.apply(VerificationCheck.java:43)
	at wycs.builders.Wyal2WycsBuilder.process(Wyal2WycsBuilder.java:811)
	at wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:208)
	at wybs.util.StdBuildRule.apply(StdBuildRule.java:109)
	at wybs.util.StdProject.build(StdProject.java:256)
	at wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518)
	at wyc.util.WycBuildTask.build(WycBuildTask.java:486)
	at wyc.WycMain.run(WycMain.java:228)
	at wyjc.WyjcMain.main(WyjcMain.java:83)
````

**Comment by DavePearce** [comment]
Hey,

Yeah, modulo arithmetic is "future work" :)

D

On 20/04/16 6:30 PM, Sebastian Schweizer wrote:
> I wanted to declare an even type, but couldn't get it working. The
> problem boils down to the following:
>
> |import whiley.lang.System method main(System.Console console): assert 2
> % 2 == 0 console.out.println(2 % 2) |
>
> Compiles without verification. Runs and prints 0.
> But it does not compile with verification:
>
> |Parsed 1 source file(s).
> ....................................................... [28ms+1mb] Typed
> 1 source file(s).
> ........................................................ [82ms+2mb]
> Generated code for 1 source file(s).
> ................................................ [9ms] [./test.whiley]
> applied definite assignment check ...................................
> [1ms] [./test.whiley] applied module check
> ................................................ [2ms] [./test.whiley]
> applied loop variants ...............................................
> [0ms] [./test.whiley] applied coercion check
> .............................................. [0ms] Whiley => Wyil:
> compiled 1 file(s) ............................................
> [197ms-5mb] Wyil => Wyal: compiled 1 file(s)
> ............................................... [33ms+1mb] Wyil => Java:
> compiled 1 file(s) ...................................................
> [23ms] Parsed 1 source file(s).
> ............................................................ [0ms]
> Generated stubs for 1 source file(s).
> .......................................... [75ms+2mb] Typed 1 source
> file(s). ............................................................
> [10ms] Generated code for 1 source file(s).
> ................................................ [5ms] [./test.whiley]
> applied macro expansion .............................................
> [1ms] [./test.whiley] Verified assertion #1 (steps: 1)
> .............................. [104ms+3mb] [./test.whiley] failed on
> verification check (assertion failed) ............... [105ms+3mb]
> ./test.whiley:4: assertion failed assert 2 % 2 == 0 ^^^^^^^^^^
> wycc.lang.SyntaxError: assertion failed at
> wycc.lang.SyntaxError.syntaxError(SyntaxError.java:341) at
> wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:220) at
> wybs.util.StdBuildRule.apply(StdBuildRule.java:109) at
> wybs.util.StdProject.build(StdProject.java:256) at
> wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518) at
> wyc.util.WycBuildTask.build(WycBuildTask.java:486) at
> wyc.WycMain.run(WycMain.java:228) at
> wyjc.WyjcMain.main(WyjcMain.java:83) Caused by:
> wycs.transforms.VerificationCheck$AssertionFailure: assertion failed at
> wycs.transforms.VerificationCheck.checkValid(VerificationCheck.java:220)
> at wycs.transforms.VerificationCheck.apply(VerificationCheck.java:164)
> at wycs.transforms.VerificationCheck.apply(VerificationCheck.java:43) at
> wycs.builders.Wyal2WycsBuilder.process(Wyal2WycsBuilder.java:811) at
> wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:208) at
> wybs.util.StdBuildRule.apply(StdBuildRule.java:109) at
> wybs.util.StdProject.build(StdProject.java:256) at
> wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518) at
> wyc.util.WycBuildTask.build(WycBuildTask.java:486) at
> wyc.WycMain.run(WycMain.java:228) at wyjc.WyjcMain.main(WyjcMain.java:83) |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Whiley/WhileyCompiler/issues/627>
>

-- 
Senior Lecturer in Computer Science,
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

Office: Cotton 231
Telephone: +64 (0)4 463 5833
URL: http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
Hey,

This is really a duplicate issue, so I'm going to close it.  The other one is: #337 (which has been open since 2014).

**Comment by SebastianS90** [comment]
Oh, thanks. Haven't seen the other one, only searched for "modulo".
