### ISSUE TITLE
Variable declarantions yield parse errors (headless statements and definite types)

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#634]
This program does not compile. "unrecognized term" for for the `function` keyword.

````
type myint is int

public export method test():
    function()->(myint) m = &(-> 1)
````

The same holds for methods.

The problem is that we end up being [here](https://github.com/Whiley/WhileyCompiler/blob/2cc45f5daea97b638d0f6bd801972a3b3cd160c8/modules/wyc/src/wyc/io/WhileyFileParser.java#L677) after `parseDefiniteType` returns `null` because `mustParseAsType` thinks we could parse it as expression.

Why not return `true` [here](https://github.com/Whiley/WhileyCompiler/blob/2cc45f5daea97b638d0f6bd801972a3b3cd160c8/modules/wyc/src/wyc/io/WhileyFileParser.java#L3377)? I cannot think of an expression that starts with a `function` or `method` keyword.

**Comment by SebastianS90** [comment]
Even shorter and probably the proof that relying on parameter/return types does not make sense:

````
public export method test():
    method()->() m = &test
````

**Comment by SebastianS90** [comment]
I tried it, does not affect any existing tests. See #635 

And this issue here should auto-close when you press merge because `develop` is now the default branch.

**Comment by DavePearce** [comment]
And so it did ... (autoclose, that is)
