### ISSUE TITLE
Subtyping of Automata

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#681]
The process for subtype testing is now that basic `Type`s are converted into `Automata` and then tested using an old, but trusty algorithm.  However, the limitations of that algorithm are now being reached.  

This issue is partly brought about by the new manner in which types are being handled.  Specifically, intersections are no longer computed immediately but, rather, are delayed using the an instance of `Type.Intersection`.

As example from `RecursiveType_Valid_3`:

```
type Expr is int | Expr[] | ListAccess
type ListAccess is {Expr index, Expr src}
type Value is int | Value[] | null

function evaluate(Expr e) -> Value:
    return 1

function evaluate(ListAccess e) -> Value:
    Value src = evaluate(e.src)
    Value index = evaluate(e.index)
    if (src is Expr[] && index is int):
        return src[index]
    else:
        return null
```

We end up trying to show that `Value` is a subtype of `Expr&Value` (which makes sense and should clearly be true).  Unfortunately, the `Automaton` representation of this question ends up being this:

`X<null|int|X[]>` is a subtype of `!(!(X<int|X[]|{X index,X src}>)|!(Y<null|int|Y[]>))`

Unfortunately, the current algorithm should cannot seem to handle this.

@richdougherty: you might be interested in this ... we definitely need a new algorithm now!

**Comment by DavePearce** [comment]
Another example from TypeEquals_Valid_29.  I am surprised this one cannot be checked though:

```
type Pos is {int col, int row}
type FilePos is {int col}
type ShortPos is Pos | FilePos

function pos2str(Pos p) -> bool:
    return true

function shortPos2str(ShortPos p) -> bool:
    if p is FilePos:
        return false
    else:
        return pos2str(p)
```
In particular, this isn't using any recursive types so it should be easier to reason about ... ?

**Comment by richdougherty** [comment]
OK, so `Type`s have a first-class intersection kind, but `Automata` still convert to union/negation? I guess we need to give automata support for intersections. It's also important to track cycles—which shouldn't be too hard now, I think. I've got an algorithm in my mind, but haven't yet had a chance to work on it!

**Comment by DavePearce** [comment]
Closing this in favour of #678
