### ISSUE TITLE
Variable Tick Notation

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#698]
In general, it would be useful to support some kind of "tick" notation using `'`.  For example, the tick of variable `x` is `x'`.  The intention is that it helps us appreciate a relationship between variables.  There are two main places this could be used:

- **Specifications**.  For example, `function update(State st)->(State st')` we're using it simply as a way to denote a connection between the input and output variables.  An interesting question is whether or not the underlying variable needs to have been declared or not.
- **Loop Invariants**.  Here, a variable `x'` can be used to represent the value of `x` on entry to the loop.  For example:
<pre>
function add(int[] xs, int item) -> (int[] ys):
    int i = 0
    //
    while i < |xs| where |xs| == |xs'|:
        xs[i] = xs[i] + item
        i = i + 1
    //
    return xs
</pre>

_The annoying thing here is the disconnect between these two different uses of the notation.  Somehow, need to align them_.

One idea might be to make the position of the tick significant.  For example, `'x` refers to old values of `x`, whilst `x'` refers to new values.

**Comment by DavePearce** [comment]
Overall, I think allowing the use of `x'` in specifications is very advantageous as adds semantic meaning.  My proposal is:

- Allow variables to be declared in the form `x'`, or `x''`, or `x'''`, etc.  Such variables can be declared only in ensures clauses.
- For any variable `x'`, it must be the case that variable `x` is previously declared in scope.

This adds clear value at relatively little cost.  An additional important question is whether or not we support this:

- For an ensures clauses using `x'`, the value of the variable is taken as the final value of `x` upon exit.

**Comment by DavePearce** [comment]
An interesting extension of this would be to support a notation of the form `x'e` where `e` is an arbitrary expression.  The intuition is that x'0 represents the value of `x` on entry to the loop (i.e. `x'` is sugar for `x'0`).

The advantage of this extended notation is that you could then specify variants in a certain fashion.

**Comment by bambinella** [comment]
I guess temporal logic is not really relevant at this point, but just in case there is some relevance:
https://en.wikipedia.org/wiki/Linear_temporal_logic

**Comment by DavePearce** [comment]
Migrated to https://github.com/Whiley/RFCs/issues/38
