### ISSUE TITLE
Support for Statically Sized Types

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#707]
(related to #654)

## Introduction

An important consideration when compiling Whiley programs for different platforms is that of _dynamically_ versus _statically_ sized types.  Roughly speaking, the former correspond to those which require dynamically allocated memory, whilst the latter correspond to those which can be entirely allocated on the stack (for example).  In particular, statically sized types have a fixed size  at compile time.

At the moment, the definition what is a dynamically sized type versus what is a statically sized type is somewhat unclear.  Essentially, any type which contains one of the following is dynamically sized:

1. **Unbound Integers**.  Any type containing an `int` which is not specifically bounded (above and below) is dynamically sized.
2. **Unbounded Arrays**.  Any type containing an array whose length is not bounded by a compile-time constant is dynamically sized.
3. **Open Records**.  Any use of an open record is dynamically sized.

To illustrate some statically-sized examples:

<pre>
type Point is { int x, int y } where 0 <= x && x <= 255 && 0 <= y && y <= 255
</pre>

<pre>
type Vec { int len, int[] data } where 0 <= len && len <= |data| && |data| <= 100
</pre>

The latter is interesting because the array itself is still variable-length, but is known to occupy a fixed amount of space in memory.

## Proposal

The primary issue with the current status-quo is that the definition of a statically sized type is somewhat awkward.  To address this issue, the proposal here is to introduce the following specific statically sized types:

- **Fixed-width Integers** (`int:8`, `int:16`, `uint:8`, etc).  These types are equivalent (in some sense) to `int`, but include an additional _size attribute_.  This attribute must be a compile-time integer  constant.  The compiler is not obliged to match the size attribute exactly in the underlying implementation, but is expected to make a "best effort".  For example, on the JVM, `int:128` may simply compile to the same underlying representation as `int` (since there is no 128bit integer on the JVM).
- **Size Type** (`usize`).  This defines the return type from the _array length_ operator.  This type is awkward since it remains unknown at any given time whether it is, for example, equivalent to `uint:32` or `uint:64`.
- **Fixed-width Arrays** (`int[8]`, `int[4]`, etc).  These types define an array of a fixed size known at compile-time.  The special type `int[?]` maybe supported to represent an array of _unknown fixed_ size, though this is not statically sized.

Here, the type `uint:8` would be the generic definition of a byte.  Likewise, a type such as `int:8[?]` is useful for describing (for example) raw pointer types in C, as this corresponds directly to `int8_t*`.

## Subtyping

An important issue is how subtyping between such types will be supported.  In fact, the proposal is that, from the perspective of subtyping, all integer types are equivalent to `int`.  This leads to some potentially precarious situations:

<pre>
function f(uint:8 x) -> (uint:4 r):
    return x
</pre>

This program appears to suffer from a _potential loss of precision_.  In many languages (e.g. Java, Rust, etc), such implicit coercions are not permitted for this reason.  However, in Whiley, we can note that the above is not a concern _because it will not verify_.  Indeed, it is roughly equivalent to this:

<pre>
function f(int x) -> (int r)
requires 0 <= x && x <= 255
ensures 0 <= r && r <= 15:
    return x
</pre>

This program will certainly fail verification.  However, we could resolve this as follows:

<pre>
function f(uint:8 x) -> (uint:4 r)
requires x <= 15:
    return x
</pre>

In this case the program would now verify and, indeed, we see _there is no loss of precision_.
## Challenges

**Platform-specific size types.** An interesting challenge is the interaction between the type `usize` and other integer types.  The general concern is that certain expressions (`arr[i]`) will not verify on some platforms (e.g. if `i` has type `int:64` on a platform where `usize` is `uint:32`. However, it seems likely that this won't be such a big problem in general.  Consider the example in more detail:

<pre>
function get(int:8[] arr, int:64 i) -> (int r):
    return arr[i]
</pre>

This exhibits the general problem.  However, the fact is that it won't verify either.  In order for it to verify, we need a precondition that `i < |arr|`, in which case there is no problem.

**Bitwise Operations.** an interesting additional question is whether or not statically sized integer types should support bitwise operations.  This would be convenient, since it would mean that `uint:8` can replace `byte`.  But, the problem is that it presumably leads to undefined behaviour for larger types (e.g. `uint:32`) due to the uncertainty of endianness?  Java handles this by treating bitwise operators as [operators on integers, not bits](http://stackoverflow.com/questions/25530342/does-the-result-of-bitwise-operations-depend-on-endianess-in-java-what-about-in).

**Comment by DavePearce** [comment]
**NOTE:** an interesting additional question is whether or not statically sized integer types should support bitwise operations.  This would be convenient, since it would mean that `uint:8` can replace `byte`.  But, the problem is that it presumably leads to undefined behaviour for larger types (e.g. `uint:32`) due to the uncertainty of endianness?

**Comment by bambinella** [comment]
I feel that maybe it should be sufficient to have a constraint on the type and only provide backend hints for representation?

That would be number of bytes, memory alignment, and byte order. The backend should know what the FFI calls require and change representation based on performance characteristics. So it could be left open for optimization.

Unless you intend to extend Whiley with the equivalent of reinterpret_cast, which probably would be a bad idea.

Although I guess aliasing from pointers returned from FFI calls is an issue.

**Comment by DavePearce** [comment]
> I feel that maybe it should be sufficient to have a regular "low<x and x<high " constraint on the type and only provide backend hints for representation?

Whilst that was my initial plan, I've eventually decided I want something more "clear cut".  I don't want people to be asking the question _"will this be compiled down to a u32?"_.  I want them to know *exactly* when it will and when it will not.

> Unless you intend to extend Whiley with the equivalent of reinterpret_cast, which probably would be a bad idea.

This won't be a problem.  The compile will handle all coercions seamlessly as necessary.

**Comment by bambinella** [comment]
>Whilst that was my initial plan, I've eventually decided I want something more "clear cut". I don't want people to be asking the question "will this be compiled down to a u32?". I want them to know exactly when it will and when it will not.

Ok, well I disagree as I don't think it is semantical and therefore is more a hint than a language feature. I think it should something parametric: eg "uint<32>", so a library type.  Where u32 is just an alias for uint<32>.

While having u32, u8 etc might make sense when you look at a single CPU it doesn't add up when you look at many. For instance, some older DSPs have 32 bit alignment and 24 bit representation. So a mere general approach that works across the spectrum would be better.

I have lots of notes on ways to approach this, but too much and incoherent to put as a comment on github...

**Comment by DavePearce** [comment]
Hey,

> I also think it should be something parametric: eg "uint<32>", so a library type. Where u32 is just an alias for uint<32>.

Hmmm, that could possibly work.  Basically, I would provide a guarantee that uint<32> compiles down to a u32 ... hmmmm.

Not sure what I think.  Ultimately, I need the compiler internals to have a notion of a fixed-width type (e.g. `int:8`) so I might as well expose that to the user for now.  Maybe I'll later retract that, we'll see.  It's hard to decide ahead of time what the real pro's and cons are.

**Comment by DavePearce** [comment]
Hey,

>  For instance, some older DSPs have 32 bit alignment and 24 bit representation. So a mere general approach that works across the spectrum would be better.

Right, then the type `int:24` works well here.

**Comment by bambinella** [comment]
On Sun, May 7, 2017 at 11:05 AM, David Pearce <notifications@github.com>
wrote:

> Hey,
>
> For instance, some older DSPs have 32 bit alignment and 24 bit
> representation. So a mere general approach that works across the spectrum
> would be better.
>
> Right, then the type int:24 works well here.
>
Well, they might repeat the most significant bit in the upper 8 bits... But
this might be a thing from the past. I am sure there are some weird
energy-efficient CPUs still, so I could look at the most common ones, on a
rainy day. They tend to have online manuals.

I grew up on 8 bit computers (machine language on C64), so I find this
stuff kinda fun and retro. :)

**Comment by bambinella** [comment]
>> type dspint is (int:32 val) where DSP_LOWER <= val && val <= DSP_UPPER
>That works better.

I think I should try to map out the things that ought to be supported based on what is used today. 

IIRC it can be as weird as this:
1. Loads from memory are 3 bytes 24 bit integers...
2. Operations in memory are 32 bit or 24 bit with sign extended most significant bit depending on the operation... E.g. 24 bit multiply, but 32 bit add...

**Comment by bambinella** [comment]
I retract the idea that it is a hint, since it doesn't only affect the backend.

One obviously should be able to query the size of an integer type for allocation purposes... same with alignment.

So it is more than an annotation.

**Comment by bambinella** [comment]
I just want to point out that one of course should be able to query for byte-size and alignment of a specific integer subtype when stored in memory.

But it still is a hint unless you want it to be a hard constraint, but then code wouldn't be as portable. And it would make more sense for the target to decide whether it should fail or not if the hint isn't fulfilled.

Otherwise people will just assume too much and not actually check for byte size and alignment...? Or maybe not. Hm.

**Comment by bambinella** [comment]
Another way to view this is to look at it from a generic programming point of view.

Maybe one should have some means to query what the hardware sizes are, and how they can be used (e.g. SIMD).

Then this could be a hard failure type if not supported efficiently, since that indicates a bug in generic code.

**Comment by bambinella** [comment]
C/C++ has types that states that they are fast or have at least so and so many bits:
http://en.cppreference.com/w/cpp/types/integer

16 bit integer types in C:

int16_t
int_fast16_t
int_least16_t
intmax_t
intptr_t
uint16_t
uint_fast16_t
uint_least16_t


That would be better "int_at_least<32>", much more specific. But still missing alignment and byteorder.

**Comment by bambinella** [comment]
>int16_t // exactly 16 bits (not available if not supported)

I don't mean that the program should fail compilation if it does not exists. I think it should fail compilation if expressions accessing it are reachable.

**Comment by bambinella** [comment]
Hm, this simple issue is more tricky then I thought... I think basically one should list all the possible use scenarios and how various definitions break or enable what the programmer is looking for.

- ability to paint types over memory mapped pages

- fast hardware support (but what operations should be selected for that definition, addition or multiplication or division?)

- fast memory load to register (does it support loading 16 bit integers from memory or does it have to load 32 bits, then shift?)

**Comment by DavePearce** [comment]
> Does it mean that the compiler isn't allowed to store u32 in 2 bytes if it can prove that 16 bits is sufficient?

Yes, this is exactly what it means.  One reason for this is to ensure interop with foreign code.  But, also so that the programmer knows exactly what will happen.

I've got to be honest here, this discussion is a bit low level.  Issues of alignment and these very subtle issues of representation are really for the (e.g. LLVM) backend. It's far from clear that I want to get down to the level of `int_fast16_t`.  

For the moment, my main focus is on some kind of Minimal Viable Product, and this is well beyond that.

**Comment by bambinella** [comment]
For MVP the most obvious solution would be to just use a type annotation
@bytes(4).

**Comment by DavePearce** [comment]
You mean instead of `int:32`?  Well, you are maybe right in that worrying about representation should be beyond what is needed for an MVP.  But, I believe it's important for good interoperation with e.g. Java or even JavaScript.

**Comment by bambinella** [comment]
> You mean instead of int:32? Well, you are maybe right in that worrying about representation should be beyond what is needed for an MVP. But, I believe it's important for good interoperation with e.g. Java or even JavaScript.

For the MVP I don't think you need an annotation at all, actually. I think you just need a type alias like (how do you create a non-nominal symbol?)

symbol u16 = (int n) where 0 <= n and n <= 65536

Then detect it in the backend and make it 2 bytes.

**Comment by bambinella** [comment]
Well in C++ templating syntax it ought to be something like this if C++ had allowed it.

`using u<16> = int16_t`
`using u<32> = uint32_t`

etc

**Comment by DavePearce** [comment]
Right, so in the stdlib file `whiley.lang.Int` there are bunch of such definitions already:

```
/**
 * Represents all signed integers representable in 8bits
 * of space in the two's complement representation.
 */
public type i8 is (int x)
    where x >=-128 && x <= 127

/**
 * Represents all signed integers representable in 16bits
 * of space in the two's complement representation.
 */
public type i16 is (int x)
    where x >=-32768 && x <= 32768

/**
 * Represents all signed integers representable in 32bits
 * of space in the two's complement representation.
 */
public type i32 is (int x)
    where x >=-2147483648 && x <= 2147483647
```
(and more)

Detecting these in the backend is what my experimental java source backend is currently doing.  It works for sure.  But, one of the problems I have with this is that detecting this in the backend makes couples the compiler and the standard library.

**Comment by bambinella** [comment]
I think you will regret it if it means that you have to extend the IR. LLVM IR is quite large...

I take it that Whiley doesn't have nominal types at this stage, what if you added "tags" that taint types in a dataflow like fashion.

So if you tag something all derived values from there-on will carry that tag as long as the constraints hold. Using flow analysis.

This could also be used for tagging an array as sorted. Any operation that modifies element order would then remove that tag.

If that would be a welcome feature then maybe you can special case i32 etc for now with a plan for removing it with a more general mechanism later?

This capability is something I have several times in C++.

**Comment by bambinella** [comment]
Such tagging could be very useful later on for people wanting to implement an optimizing backend for linear algebra calling vendor provided BLAS routines and the like.

**Comment by bambinella** [comment]
How about this:

1. A property can represent the name and constraints of a tag.

2. There is an standardized ontology of properties with names which the backend may know.

3. The IR is extended so that "taggable properties" can be represented.

4. The backend can easily work with these tags (just numeric ids) and doesn't have to detect anything.

**Comment by DavePearce** [comment]
> Such tagging could be very useful later on for people wanting to implement an optimizing backend for linear algebra calling BLAS routines and the like provided by CPU/OS vendor.

Note that this is not a major use case from my perspective at this stage.

**Comment by bambinella** [comment]
Well, it would also help when adding floating point without touching the verifier... I think.

**Comment by bambinella** [comment]
Btw, if the primary need for this is for FFI, wouldn't it be sufficient to do this as an annotation of the parameters in the function signature? The the compiler can deduce that other types should have a FFI compatible representation for efficiency reasons if type conversion is identified as a bottleneck.

**Comment by DavePearce** [comment]
I'm gonna write this up as an RFC shortly and then we can look at it.  Ultimately, I'm pretty confident this is what I want to do.

**Comment by bambinella** [comment]
Looking forward to the RFC. If you focus on FFI then you should also focus on vectorized register parameters which is happening now because 64 bit X86 now have all registers vectorized. But you probably can model this as tuples.

https://software.intel.com/en-us/articles/vectorcall-and-regcall-demystified
https://msdn.microsoft.com/en-us/library/dn375768.aspx
http://lists.llvm.org/pipermail/llvm-dev/2016-November/107679.html

**Comment by DavePearce** [comment]
This is now an RFC under review here: https://github.com/Whiley/RFCs/pull/3
