### ISSUE TITLE
Suggestion: templates and concepts/type classes

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#723]
Before adding templates I think it would be worthwhile to take an open-minded look at what C++ has done with concepts:

http://en.cppreference.com/w/cpp/language/constraints

And what haskell has done with type classes:

https://www.haskell.org/tutorial/classes.html

**Comment by DavePearce** [comment]
Ok, I'm going to put this under the existing issue for template syntax in Whiley.
