### ISSUE TITLE
Suggestion: libraries worth porting to Whiley

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#724]
I have found that having the same implementation of an encryption library on multiple platforms to be very useful. It saves me from the risk of getting compatibility issues, hence less debugging. Not all platforms allow linking to C. Therefore Whiley!

Therefore translating  "liberal licensed" crypto libraries to Whiley would be a nice addition, and more and more useful the more backends Whiley gets.

Perhaps a bit hard on the prover... :-D

**Comment by DavePearce** [comment]
Yes, crypto libraries are something I'm interested in.  I think Whiley could be useful here, though it's a hard topic and I'm putting it off for now.

**Comment by DavePearce** [comment]
FYI, as an aside I came across this just today:

http://drops.dagstuhl.de/opus/volltexte/2017/7119/pdf/LIPIcs-SNAPL-2017-1.pdf

This definitely something I would like to implement and verify in Whiley.  It's probably still a way of before Whiley is ready for such a challenging task, but anyhow ... it's a goal.
