### ISSUE TITLE
Compile-Time Conditionals for Meta-Programming

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#726]
It is often useful to put a constraint on something suggesting that it has to be resolved at compile time. This is to ensure performance gains or to prevent some kind of bloat from occuring. It would be nice if this was done with a uniform syntax across the board.

Conceptually it could be like this:

`function f(int §x, int y)->...:`
`    if §(expression)...`

x and expression has to be resolved (or at least be resolvable) at compile time at the location where f is called.

I think perhaps a different symbol should be used. The mnemonic of "§" suggests referencing, querying or establishing a rule in the more general sense.

Maybe "§" could be read as "resolution". Then "§§" could be used for querying properties of the program, but that would perhaps look a bit noisy.

**Comment by DavePearce** [comment]
In D, this is a `static if` I think:

https://dlang.org/templates-revisited.html

**Comment by DavePearce** [comment]
This is related to #540

**Comment by bambinella** [comment]
No, D is not able to solve propositions or predicates... Everything has to be done using explicit values that is computed during compilation.

"static if" is a rather ad-hoc quasi-syntactical construct where I believe either the then-branch and the else-branch undergo semantic analysis based on the condition being true or false.

It is more like a macroish feature.

In C++ they have `if constexpr …` which is similar but restricted so that both branches pass type-checking.
