### ISSUE TITLE
Annotation Syntax

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#727]
Having a uniform signifier for non-semantic information is handy. It means that editors can choose to hide it to clean up the visuals or render it in grey.

Maybe prefixing such annotations with "@" would be reasonable. Or is it too noisy?

Use case: it is often tedious to wait for a compiler to optimize at the highest level, so it would be nice to just enable the highest optimization where you need it by putting "@faster" or something more specific where you need it. That way debug builds can perform ok and still get decent compiles with minimal configuration effort.

**Comment by DavePearce** [comment]
Annotation syntax is something I've been thinking about.  It is useful, I agree.

**ACTION:** to make progress on this, we need to come up with an actual proposal.  The main question is: where would `@annotation` annotations be allowed?  For example, only on function/method/type declarations?  as in:
```
@test
method test_35() -> int:
    ...
```
Or, also on parameters + local variable declarations?  as in
```
method test_35(@extern int[] xs) -> int:
    @extern int[] ys = xs
    ...
```
Or, also on components of types? as in
```
method test_35((@extern int)[] xs) -> int:
    ...
```
_The key challenge with making progress here is that we need an actual use case.  At the moment, I just don't have anything._

**Comment by DavePearce** [comment]
[Attributes in Rust](https://doc.rust-lang.org/book/attributes.html) are worth looking at.  They are definitely more powerful that annotations in Java.

**Comment by DavePearce** [comment]
Migrated to https://github.com/Whiley/RFCs/issues/27
