### ISSUE TITLE
Suggestion for syntax: consider moving types to the right before adding templates

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#728]
Whiley is currently looking clean by having the type on the left, just like pre-templating languages like C and Simula.

However when you add metaprogramming/templating you will find that the type-names become unbearably long in large programs which makes the code look untidy. This is why I find C++ source to be much more chaotic than newer languages like TypeScript. I personally prefer the TypeScript way of "x:type", but maybe not right for Whiley.

Just to illustrate the difference:

`somestuff<otherstuff,23,configuration<T,199,2000>> x`
`link<node,3> y`
`fouriertransform<windowfunction<gauss>,2048> fft`

versus:

`x: somestuff<otherstuff,23,configuration<T,199,2000>>`
`y: link<node,3>`
`fft: fouriertransform<windowfunction<gauss>,2048>`

**Comment by DavePearce** [comment]
Right, I'm going to be honest here: I simply do not like `x : T` notation.  I as far as I'm concerned the syntax is settled for `T x` notation and, hence, I am going to close this issue,

Ultimately, I have to say that your argument is far from convincing.  I don't see much or any improvement between the two examples.  They are about as bad as each other.  What we should recommend is that people use type aliases for this kind of situation:
```
type mystuff is somestuff<otherstuff,23,configuration<T,199,2000>>

mystuff x = ...
```
That's good enough.
