### ISSUE TITLE
Suggestion: generic programming, coercing failed assertion to false in boolean expression

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#729]
In generic programming it might be useful to have two alternative expressions or code blocks, where the faster version is executed if an assertion is proven to hold else the other branch is taken:

Conceptually (syntax should be harmonized with other features that are required to resolve at compile time):

`if §§assert(expression):`
`    fast_path...`
`else:`
`    slow_and_safe`

**Comment by DavePearce** [comment]
C++ templates allow for this kind of thing using specialisation.  So, perhaps, this could be one use case for allowing overloading on `requires` clauses #725.

But, I have to be honest, this is really a long way off in the future.  We need a mechanism for generic programming first ...

**Comment by bambinella** [comment]
>C++ templates allow for this kind of thing using specialisation. So, perhaps, this could be one use case for allowing overloading on requires clauses #725.

Hm. Not sure what you mean with C++. You perhaps mean that it ignores instantiation failure which is used for selecting between multiple definitions? I guess that could be viewed as related. Although in C++ the "verifier part" is just the type system.

What I meant though was that the fast_path could be taken if you just hooked Whiley up with a bigger/better verifier (e.g. run the verification stage on a cluster ).

But not limited to conditionals, it could work with any boolean expression.

**Comment by DavePearce** [comment]
I mean that you can use specialised templates to cover "fast paths".  Not sure what a good example is, but here's some discussion of it: http://www.gotw.ca/publications/mill17.htm

**Comment by bambinella** [comment]
Hm. The way I read that gotw thing it just states that you cannot overload on template specializations, so more about a weakness in C++?

But SFINAE http://en.cppreference.com/w/cpp/language/sfinae is kinda similar. Except for the "verification" part.

**Comment by bambinella** [comment]
Oh wait, maybe you mean something like `if constexpr(expr)`?

http://en.cppreference.com/w/cpp/language/if

**Comment by DavePearce** [comment]
The point is that you take a template function e.g.

```
template<T> 
void f(T x) { ... }
```
and you can then write an explicit specialisation of it for a particular type, e.g.
```
template<> 
void f(int x) { .. }
```
(not quite sure I'm remembering the syntax here)

It's not exactly what you're describing.  But, it does allow a similar effect.  Furthermore, with overloading on preconditions you could get close to what you wanted above.  For example:
```
function f(int x): // slow path

function f(int x) requires ...: // fast path
```
This is one use case for overloading on `requires` clauses I have considered.

**Comment by bambinella** [comment]
> function f(int x): // slow path
> function f(int x) requires ...: // fast path

This is  what I meant, if allow the slow path to be taken when the requires clause is too difficult to prove or disprove.

But maybe you feel that such overloading should only be done if the requires clause can be resolved with certainty (resolved as true or false, not merely a unknown)?

**Comment by DavePearce** [comment]
At this stage, I'm not sure what I think about it.  To be honest, from my perspective, it's not on the critical path and is something which can be added later.  I think the first thing is to figure out a proper template syntax, implement that and also a good native backend (e.g. LLVM).  After all of that, we would then be in a point where we might have concrete use cases where we wanted to do this ...

**Comment by DavePearce** [comment]
At this stage, I'm closing this issue.  It possibly could go under #540 or on the wiki.
