### ISSUE TITLE
Future: verification over global CPU feature check

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#732]
CPUs have different features, meaning that different instructions are available or not, or that that some instructions come with expensive penalties.

However it is also sometimes desirable to supporting multiple CPUs in the same build.

So it would be interesting if it was possible to prove that an instruction (FFI call) isn't executed unless it has been established at runtime that it is available. Without doing an explicit runtime-check before executing the instruction.

It might also be interesting to have a statement that ensures that a specific instruction set is available and enabled in the backend in a particular loop.

Maybe flow analysis can be used to turn on instruction availability in the backend in code where a CPU runtime check has been established for that instruction (or set of instructions)? With a matching availability assertion to be used in performance-critical loops.

**Comment by bambinella** [comment]
I guess there are other things that could be done in relation to this.

Basically asserting that various alternate versions are turned on in a loop. Then the compiler will move the check outside the loop and generate multiple loops based which instructionset you have. E.g. one for AMD and another for new Intel, and yet another one for old Intel CPUs.

**Comment by DavePearce** [comment]
This is definitely something for the backend.  It's not really an issue for the WhileyCompiler (which is the front end).
