### ISSUE TITLE
Backend: Clean codegen for optimized code using deforestation?

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#733]
Just remember reading papers about legacy software written in ancient languages being refactored using deforestation. Basically expanding and then looking for similarities before translation to another language.

I wonder if deforestation could be used for creating readable code after an agressive inlining-unrolling-optimizing expansion.

I will add papers to this thread later:

https://www.eecs.northwestern.edu/~robby/courses/395-495-2017-winter/deforest.pdf

(Or maybe this issue belongs in the compiler collection repo?)

**Comment by bambinella** [comment]
Deforestation might also be used for cutting down on template bloat at a later stage.

**Comment by DavePearce** [comment]
I'm not really sure what the connection with Whiley is here.  I think it has some connection with what is called "clone" elimination.  See here:

https://www.researchgate.net/profile/Laurie_Hendren/publication/221302771_Staged_Static_Techniques_to_Efficiently_Implement_Array_Copy_Semantics_in_a_MATLAB_JIT_Compiler/links/556c638008aec226830489d1.pdf

See also this:

https://www.researchgate.net/publication/312012802_Static_techniques_for_reducing_memory_usage_in_the_C_implementation_of_whiley_programs

And, this is related to issue #706.  But, overall, this is not an issue for the WhileyCompiler at this stage.  Perhaps if you rephrase the issue in more detail?
