### ISSUE TITLE
Support Difference Verification Levels

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#735]
Since different verifiers might be able to handle different asserts and since templated code easily could lead to "impossible" asserts then there ought to be some way of specifying the importance and context of assert/pre/post conditions. Some kind of classification mechanism.

This would enable:
1. Doing cheap verification during IDE sessions.
2. Doing expensive verification for release builds.
3. Emitting runtime asserts.
etc

**Comment by bambinella** [comment]
Another aspect of this is enable solid, but efficient, run-time asserts in generated libraries that are to be integrated with other languages. So that the user can select various options for runtime checks, but never pay for expressions that have already been proven before code-gen.

**Comment by DavePearce** [comment]
>  enable solid, but efficient, run-time asserts

Yes, this something that is sort of supported now, but needs more work.  Also, in making it efficient.

**Comment by bambinella** [comment]
Maybe at sometime in the future there will be multiple verifiers, perhaps some external. First a fast and simple verifier that turns some asserts into assumes, then a more heavy verifier deals with the remaining ones... etc. Cascading.

**Comment by bambinella** [comment]
Maybe at sometime in the future there will be multiple verifiers, perhaps some external. First a fast and simple verifier that turns some asserts into assumes, then a more heavy verifier deals with the remaining ones... etc. Cascading.

**Comment by bambinella** [comment]
Duh...

**Comment by DavePearce** [comment]
Some of this is supported already through the prover "--limit" option.  However, this is not available as a command-line option when invoking the whiley compiler itself (though it should be).  Certainly, other command-line options would be good.

**Comment by bambinella** [comment]
Oh, sorry, thought I had made a typo... didn't see your changing it to "difference". :)
