### ISSUE TITLE
Backend: floating point

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#737]
https://www.csee.umbc.edu/~tsimo1/CMSC455/IEEE-754-2008.pdf

Intel instruction manual:
http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf

AMD instructions:
http://support.amd.com/TechDocs/26568.pdf

Floating point bit-explorer tool (online javascript app):
https://www.h-schmidt.net/FloatConverter/IEEE754.html

How the Intel compiler deals with floating point optimization:
https://software.intel.com/sites/default/files/article/326703/fp-control-2012-08.pdf

Intel intrinsics guide (online browser):
https://software.intel.com/sites/landingpage/IntrinsicsGuide/

Instruction performance on various CPUs (cycles, throughput):
http://www.agner.org/optimize/instruction_tables.pdf

(adding more useful links later)

**Comment by DavePearce** [comment]
This is not really a WhileyCompiler issue.  Floating point is something to be handled with in a library or in a backend.  I would create a repository for `WhileyLLVM` and put this issue there.  That is, how to compile existing Whiley code to use floating point.
