### ISSUE TITLE
Future: meta-programming, accessing external data files as  Whiley "facts".

### ISSUE THREAD

**Issue by bambinella** [Whiley/WhileyCompiler#740]
In real world programming scenarios one often ends up writing scripts that turn data-files into code. Often one also have to update multiple locations with the same data, manually.

It would be very useful to have a feature where the programmer could specify a "lazy" transform from XML/JSON/tab-separated-file to Whiley.

The goal is to make the data available in Whiley-code through some query mechanism, a transform into constants or some other "injection" method.

This might also be useful when making productivity tools for the language.

**Comment by DavePearce** [comment]
In Rust you can do this using Macros:

http://stackoverflow.com/questions/32956050/how-to-create-a-static-string-at-compile-time

I have found some situations where this is useful.  For example, in creating a Z80 emulator it's useful to include the boot ROM as a compile-time constant from a file.

**Comment by DavePearce** [comment]
Right, I have migrated this issue into the wiki.  It's really part of a larger discussion on what meta-programming support should be provided in Whiley:

https://github.com/Whiley/WhileyCompiler/wiki/Meta-Programming
