### ISSUE TITLE
Syntax for Fully Qualified Names

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#742]
Currently, the mechanism for representing a fully qualified name is based on that of Java.  Namely, it uses the "dot" syntax whereby we have names such as `whiley.lang.Int` and `whiley.lang.Int.u8`.  One difficulty with this syntax is that we cannot distinguish _paths_ from _names_:

- **Path**.  A path identifies a specific Whiley file within a specific package.  For example, `whiley.lang.Int` identifies file `Int.whiley` in package `whiley.lang`.
- **Name**.  A name identifiers a named declaration within a specific Whiley file.  For example, `whiley.lang.Int.u8` identifiers the type declaration `u8` within the Whiley file `whiley.lang.Int`.

There are a number of ways in which we could syntactically distinguish paths from names.  Some examples:

- `this.is.path:Name`.  Thus, for our two examples above we would have `whiley.lang.Int` and `whiley.lang.Int:u8`.  A short form of the latter would be `Int:u8`.
- `this::is::path.Name`.  Thus, for our two examples above we would have `whiley::lang::Int` and `whiley::lang::Int.u8`.  A short form of the latter would be `Int.u8`.

The latter is perhaps somewhat closer to [Rust's name syntax](https://doc.rust-lang.org/beta/book/second-edition/ch07-03-importing-names-with-use.html).

There are some implications here.  In particular, it means there is a strong distinction between a file and a potentially nested namespace.

**Comment by bambinella** [comment]
I find the C++ "::" notation to be noisy. I think Ada is more clean:

whiley'lang'Int

**Comment by DavePearce** [comment]
Currently, I think I'm now leaning towards the C++ / Rust style.  One reason for this is simply that Whiley wants to compete in this space.  This would also mean a flatter hierarchy for the standard library.  For example, we'd have something like this:

- `std::ascii` --- For all ASCII related stuff (currently `whiley.lang.ASCII`)
- `std::io` --- For all basic definitions of readers / writers (currently `whiley.io.Reader`, `whiley.io.Writer`, etc).
- `std::array` --- For all array manipulation functions (currently `whiley.lang.Array`)
- `std::int` --- For all integer coercion operations, and other functions (e.g. parsing integer from string) (currently `whiley.lang.Int`)
- `std::math` --- For all math related functions, e.g. `abs()`, `min()`, `max()`, `gcd()`, etc (currently `whiley.lang.Math`).

The big question is how to handle nested modules.  Of couse, just `this::is::nested` is an easy approach.  But, if we want to distinguish name spaces within modules it could be interesting.  Perhaps, for exaple, `this/is::nested`.  Hmmmmm

**Comment by DavePearce** [comment]
Having now refactored the standard library roughly as above following [RFC#0007](https://github.com/Whiley/RFCs/blob/master/text/0007-refactor_stdlib.md), I'm starting to the think the syntax `std/ascii:string` is perhaps more preferable.  Here, `std/ascii` is the module path, and `string` the named item (in this case a type declaration).  Some notes

* In general, you would e.g. `import std/ascii` and then refer to e.g. `ascii:string` which works nicely.
* C++ and Rust, for example, don't have a strong notion of what it means to be inside a module.  For C++, this is partly because of how  `#includes` work.  I'm not sure why they do this for Rust.  If we followed Rust, for example, then we would `import std::ascii` and then refer to e.g. `ascii::string`.  In Rust, however, when you import a module you import all the named items contained therein.  

Needs some more thoughts.

**Comment by DavePearce** [comment]
Right, final thoughts now.  Having spent a fair bit of time refactoring the standard library, I think this is the final word:
```
import std/ascii
import std/io

method main(ascii::string[] args):
   io::println("Hello World")
```

This seems to be a useful compromise.  It provides both a strong notion of "inside" versus "outside" whilst also retaining the feel of existing systems languages like C++ and Rust.

The next interesting question which should arise is what recommended naming conventions should be used.  Looking at the [Rust naming conventions](https://aturon.github.io/style/naming.html) is useful here.  Currently, I definitely agree with:

1.  **Lower case for module names**.  Thus, 'std/io', 'std/ascii', etc.  But, not e.g. 'std/ASCII'
2. **CamelCase** for compound types (i.e. records).

The real question is whether or not to go with `snake_case` for functions / methods.  Currently, I've been following Java and using `camelCase` with lower case first.  Thus, we have `filesystem::open`, `ascii::toString()`, etc.  But, perhaps it should be `ascii::to_string()` ?

**Comment by DavePearce** [comment]
Ok, have written this up as an RFC now here:

https://github.com/Whiley/RFCs/pull/13

Therefore, am closing this issue.
