### ISSUE TITLE
Implementing Nominal Types in Whiley

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#758]
This is not an issue rather it's more of an observation (which could be written up into an RFC).  The idea was suggested by Gary Leavens.  Basically, suppose we want a mechanism for implementing true nominal types in Whiley.  To do this, we could introduce a special type (say `nominal`) for which we can (somehow) generate unique values.  This is a little like "branding" in Grace (see [here](http://drops.dagstuhl.de/opus/volltexte/2015/5231/pdf/21.pdf)).

However, Gary suggests an alternative.  Specifically, we can reuse lambdas for this.  This depends a little on the semantics for lambdas.  For example, consider the following:

```
type lambda is function()->(int)

function create() -> (lambda r):
    return \( -> return 0)
```

The question now is: could `create() == create()` ever hold?  That is, does `create()` always return a completely fresh lambda?  This is an interesting question.  Of course, it means that we need to consider the meaning on equality on lambdas.

Anyhow, if lambdas construct new values ... then we could use them as brands.

**Comment by DavePearce** [comment]
@zmthy you might be interested in this.

**Comment by zmthy** [comment]
What's the motivation for this in the context of Whiley? Do you really need nominal types if you don't have references?

Equality between functions is a pretty thorny topic. The safest course of action is to not define it.

**Comment by DavePearce** [comment]
Hey Tim,

(I'm back now, and starting to get a grip on reality)

Good question what the motivation is.  To be honest, it's as much as anything a simple observation that this might be enough.  I hadn't considered it until Gary suggested it.

I suppose one situation where this might be useful.  Suppose we're translating Java programs into Whiley programs.  Then we need a simple mechanism for branding classes in general fashion.  This approach would probably do the trick, and I don't think there are any other solutions in Whiley without further syntactic extensions.  Hmmm, well actually using a `string` to represent the class name would work.  But, then comparing classes is less efficient as it equates to `string` comparison.

Anyhow, just a thought ...

(congrats on being a Dr now, btw)

**Comment by bambinella** [comment]
I think some kind of nominal typing is needed for operator overloading ergonomics, convenient type safety, and convenient runtime type resolution.

Just a thought, but if you had a "symbolic" set-like type and only allowed aggregates (records/structs) to be used for nominal types then you could get nominal typing implicitly by having "symbol" fields in aggregates and match on those (usually just a "type" field). Then getting rid of that field in code-gen would be an optimization. A plain structural type could then set a "type" field to the set of all symbols or have multiple ones (perhaps compiled down to a single field at runtime or removed altogether if it resolves at compile time).

It could replace ad-hoc C++ bit-field enum-sets. Let the compiler find the most common set operations and pick the most efficient representation (or use a constraint that limit the combination of symbols, for instance to ban incompatible states).

I think a solution along the lines of a "symbol" type would be the most generic one and could open up for interesting generics support at a later stage. But would also be more verbose and perhaps too flexible and "low level" for Whiley.

But it really depends on the application area for the language. If Whiley is going to become a systems development language then I think it would be interesting to look at common idioms in C/C++ and try to make something more generic that allows the compiler create smarter code automatically while retaining representation control where needed.

E.g. maintaining bit-sets in C++ for typing is a chore and error prone, and using classes with type-info might be inefficient. A language that can do both behind the scenes, based on constraints, could be provide better programmer ergonomics.

Being able to relate existing C/C++ idioms to Whiley mechanics also have some educational value.

**Comment by DavePearce** [comment]
Hey Ola,

> I think some kind of nominal typing is needed for operator overloading ergonomics,

Not sure I'm totally following you here?  Definitely I want to support operator overloading in the future though ...

**Comment by bambinella** [comment]
> Not sure I'm totally following you here? Definitely I want to support operator overloading in the future though ...

The difference between say a vector, distance and position:
position - position => distance
position + distance => position

**Comment by DavePearce** [comment]
> The difference between say a vector, distance and position:

Right, I see.  Actually this should be supported already in even without direct fully for nominal typing (in the true sense of the term).  This is because Whiley does now retain complete nominal information into the flow typing stage.  It means that we should be able to distinguish calls to these functions:

```
function length(ascii.string s1):
   ...
function length(utf8.string s1):
   ...
```

Under the hood both `ascii.string` and `utf8.string` have type `byte[]`.  Thus, the following two invocations should compile correctly:

```
ascii.string as = ...
int al = length(as) // yes, OK
```

```
utf8.string us = ...
int ul = length(us) // yes, OK
```

However, this should produce a compilation error saying it's ambiguous which one to choose:

```

```
byte[] bs = ...
int al = length(bs) // no OK, can't tell which one
```

Unfortunately, at the moment, there is a compiler bug which is preventing this overloading scheme from working:

https://github.com/Whiley/WhileyCompiler/issues/702

But, over the coming weeks/months I will now begin to tease out all the remaining annoying little bugs like this...

**Comment by DavePearce** [comment]
Migrated to https://github.com/Whiley/RFCs/issues/26
