### ISSUE TITLE
Internal failure: cannot convert expression to atom: 108

### ISSUE THREAD

**Issue by dylan-chong** [Whiley/WhileyCompiler#808]
```
function f(int[] x, int[] y) -> (bool r)
requires |x| >= 1
requires |y| >= 1
ensures r <==> (
    all { i in 0..0 | x[i] == y[i] }
):
    return true
```

Produces error: `Internal failure: cannot convert expression to atom: 108`
Using WhileyWeb at commit `5b02f9e46a07a8c53b112fcb532bcfbd49dc08aa`

**Comment by dylan-chong** [comment]
Potentially relevant:

```
function f(int[] x, int[] y) -> (bool r)
requires |x| >= 1
requires |y| >= 1
ensures r <==> (
    no { i in 0..0 | x[i] == y[i] }   // unrecognised term 'no'
):
    return true
```

**Comment by Aristarkh4** [comment]
Same issue in several functions with "r <==> quantifier condition" constructions in ensures section:

```
function contains(int x, int[] a) -> (bool r)
ensures r <==> some { i in 0..|a| | a[i] = x }:
    r = true
    int k = 0
    while k < |a|:
        if a[k] == x:
            r = false
        k = k+1
    return r
```

**Comment by DavePearce** [comment]
Hey,

Ok, noted about `<==>`.

The `no` quantifier hasn't been supported for a while.  You can also workaround this using either `all` or `some`.

**Comment by DavePearce** [comment]
Right, migrated issue regarding `<==>` to the theorem prover:

https://github.com/Whiley/WhileyTheoremProver/issues/137

Should be easy to fix.  Will do now and release updated version later today.

**Comment by DavePearce** [comment]
An, migrated `no` quantifier issue to specific one here: #810

**Comment by DavePearce** [comment]
The problem with `<==>` is now fixed and live on `whileylabs.com` --- thanks for pointing out the problem!!
