### ISSUE TITLE
Generation of Unqualified Synthetic Names

### ISSUE THREAD

**Issue by dylanmckay** [Whiley/WhileyCompiler#816]
When I try to run this Whiley program via [Whiley Labs](whileylabs.com)

```
import std::io

function arrayConcat(int[] a, int[] b) -> (int[] c)
requires true
ensures true:
    return [1]
    
method main():
    io::println(arrayConcat([1], [2]))
```

I get this error message on the `io::println` line.

```
name "ascii::string" not found
```

I have not referred to this type, nor am I actually directly using strings.

The same thing happens when I attempt to do `io::println("foo")`

**Comment by DavePearce** [comment]
Hmmm, I see you're the LLVM AVR guy.  We should talk about that sometime!  I definitely want to see Whiley running on embedded systems...

**Comment by dylanmckay** [comment]
> `import std::ascii`

That makes sense, thanks!

> Hmmm, I see you're the LLVM AVR guy. We should talk about that sometime!

Definitely sounds interesting! Agree that embedded systems work really well with languages like Whiley (and [Rust](https://github.com/avr-rust/rust)).

It is quite likely we will meet anyway, as I'm a second year VUW student and you have previously coordinated one of my courses 😀

**Comment by DavePearce** [comment]
> Definitely sounds interesting! Agree that embedded systems work really well with languages like Whiley (and Rust).

Yeah, Whiley is taking some inspiration from Rust.  And, here are some embedded systems I want to get it running on:

https://twitter.com/whileydave/status/700147864429723648
(That's an AMTEL ATTINY 85)

https://www.youtube.com/watch?v=lVehvLJZumE&t=49s
(we had an ENGR489 project targeting this via C, see here: http://ecs.victoria.ac.nz/~djp/files/MattStevensENGR489.pdf)

> It is quite likely we will meet anyway, as I'm a second year VUW student and you have previously coordinated one of my courses 😀

Fair enough, and I'll be back in the new year.  So maybe we should catch up for coffee sometime.

**Comment by dylanmckay** [comment]
> (That's an AMTEL ATTINY 85)

So far as the Tiny chips go, the AVR LLVM backend support isn't that great. From memory, the Tiny chips have a special 32-bit store instruction which isn't implemented by the backend yet. [Here](https://github.com/avr-llvm/llvm/labels/tiny-core) is a list of issues affecting the Tiny cores if LLVM was ever used by Whiley in the future.

> So maybe we should catch up for coffee sometime.

Sounds like a plan, feel free to contact me at the email address listed on my [homepage](https://dylanmckay.io/) when you're back in town, otherwise I'll probably hit you up early next year

**Comment by DavePearce** [comment]
This bug has now been fixed at some point since the original example now compiles.
