### ISSUE TITLE
Expected end-of-line when using a 'in' operator

### ISSUE THREAD

**Issue by dylan-chong** [Whiley/WhileyCompiler#824]
Here are two situations where the 'in' operator does not appear to compile

```typescript
type MyEnum is (int e) where e in ['A', 'B', 'C'] // expected end-of-line
```

```typescript
function f() -> (bool r):
    int[] a = [1, 2]
    r = 1 in a // expected end-of-line 
    return r
```

**Comment by dylan-chong** [comment]
Random tip: Use the typescript syntax highlighting!

**Comment by DavePearce** [comment]
Actually, that's not valid syntax.  It used to be, but not anymore (though perhaps maybe again in the future).  There is no `in` operator.  The only situation you can use `in` is in the context of a `all` or `some` quantifier.  The reason I took this out was just to simplify the language.  I was having a lot of problems with verification here, and I just cut it out for now.

**NOTE:** interesting about TypeScript highlighting.  I guess it's quite a good fit.  On Wikipedia, you can already use whiley as a language.  I need to get this setup on github at some point as well ...
