### ISSUE TITLE
Update field inside a type

### ISSUE THREAD

**Issue by samminweng** [Whiley/WhileyCompiler#831]
We tried to write a method to update a field inside a structure.
In Java, we can have the below code
```
class Vector {
        int x;
        int y;
        public void reset(){
            x=2;
            y=2;
        }
    }
```
In Whiley, we come up with the below code to update 'x' and 'y' in a vector object
```
type Vector is &{
    int x,
    int y,
    method reset(Vector)
}
method f(Vector v):
    (*v).x = 2
    (*v).y = 2
    return
method main():
    Vector vector = new {x:0, y:0, reset:&f}
    assert (*vector).x == 0
    (*vector).reset(vector)
    assert (*vector).x == 2
```
Not sure if we are using correct Whiley syntax, and wonder if there is any alternative way of doing this. Any help is appreciated. 

Sam

**Comment by DavePearce** [comment]
Hey Sam and Mark (@utting),

_(I'm back from Africa now and starting to catch up on stuff)_

Hmmmm.  I mean this looks pretty good to me.  It's roughly how I would imagine doing it, _if I were going to use references_.  Is there an issue with this approach you're having?  It seems to compile OK for me, though it won't verify.  This bit of the translation is ugly I know `(*vector).reset(vector)` and I don't have a better solution right now.

Depending on what exactly you're trying to do, the other option is to thread the record through.  This way you can avoid references, and it goes something like this:

```
type Vector is {
    int x,
    int y,
    method reset(Vector) -> Vector
}

method f(Vector v) -> Vector:
    v.x = 2
    v.y = 2
    return v
    
method main():
    Vector vector = {x:0, y:0, reset:&f}
    assert vector.x == 0
    vector = vector.reset(vector)
    assert vector.x == 2
```

Let me know what you think.

**Comment by samminweng** [comment]
The second option with reference is much better and what we are looking for. Thanks.

Sam

**Comment by DavePearce** [comment]
Great!
