### ISSUE TITLE
error: WHILEYHOME environment variable not set

### ISSUE THREAD

**Issue by sammaphey** [Whiley/WhileyCompiler#852]
Hi,

Just started trying to mess around while the whiley dev kit. Downloaded the wdk from http://whiley.org/downloads/ (version 0.4.2). 

Added the variable to my $PATH (using a mac so added the line /usr/local/wdk-v0.4.2/bin to /etc/paths file). 

running the example from your site `wy jvmcompile hello_world.whiley` I receive this error:
error: WHILEYHOME environment variable not set

Java version info:
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

Any help would be much appreciated!

**Comment by sammaphey** [comment]
Realized that this is in the wrong thread and should instead be under WhileyDevelopmentKit repo. 

Solved the problem: For those on mac `export WHILEYHOME=/usr/local/wdk-v0.4.2` (/usr/local is just where I happened to install the package.)

**Comment by DavePearce** [comment]
Interesting about `/etc/paths`.  I'm not familiar with that.  Hmmm,

https://unix.stackexchange.com/questions/356688/whats-the-difference-between-echo-path-vs-etc-paths

It could be that you need to reboot the machine after editing that file?  Seems like it should work I think.  

You can edit your `.profile` file and do it there as well.
