### ISSUE TITLE
 Fix NegativeArraySizeException in Record_Valid_5

### ISSUE THREAD

**Issue by JC626** [Whiley/WhileyCompiler#859]
Similar to #857

Hand function fails when `cards` is an empty array.

Due to:

```
property sorted(Card[] cards)
where all { i in 1..|cards| | lessThan(cards[i-1],cards[i]) } 
```

**Comment by DavePearce** [comment]
What actually happens?  It goes into a loop or something?  I think it's a bug in the interpreter more than anything.
