### ISSUE TITLE
Precondition function check throws NullPointerException

### ISSUE THREAD

**Issue by JC626** [Whiley/WhileyCompiler#861]
In 013_btree\main.whiley , the following input throws a `NullPointerException` when checking the precondition for the `function Node(int data, Tree left, Tree right) -> Node`.

[-5, {data:-5,left:null,right:null}, null]

This is due to the `Interpreter` unable to find the `elts` function in `executeInvoke`. Specifically

`Decl.Callable decl = typeSystem.resolveExactly(expr.getName(), expr.getSignature(), Decl.Callable.class);`

sets `decl = null`. This could be because the type signature given for the `expr` is `(???)->(???)` whereas `elts` type signature is `(Tree t) -> (int[] ret)`.

**Comment by DavePearce** [comment]
Hmmmm, this is tricky.  What we need ideally is a minimal test case that recreates the issue.  Ideally, the smallest possible self-contained program which illustrates the problem.

**Comment by DavePearce** [comment]
Ok, here's what I came up with:

```
function check(int[] args) -> bool
// No element of args can be negative.
requires all { i in 0..|id(args)| | args[i] >= 0 }:
    //
    return true

function id(int[] args) -> (int[] rs)
ensures |args| == |rs|:
    //  
    return args

method main():
    assert check([1,2,3])
```

**Comment by DavePearce** [comment]
Ok, have added this test case.  But, seems this bug is already fixed in latest development snapshot.
