### ISSUE TITLE
Duplicate functions or methods allowed

### ISSUE THREAD

**Issue by SimonPope** [Whiley/WhileyCompiler#862]
When there are two functions or methods with the same name and arguments, the program still compiles and verifies without issue. For example, the following code compiles and verifies:

    function test(int a):
        int i = a
    
    function test(int a):
        int i = a

It is only when you attempt to invoke the function that the compiler throws the error:
> unable to resolve name (is ambiguous)

**Comment by DavePearce** [comment]
Great --- thanks for pointing this out Simon!

**Comment by DavePearce** [comment]
Fixed through #939 and the addition of a `SignatureCheck` stage in the compiler.
