### ISSUE TITLE
Definite assignment for global variables not checked

### ISSUE THREAD

**Issue by JC626** [Whiley/WhileyCompiler#864]
The following example can be compiled and executed.

```
int a = b * 2
    
int b = 1

method main():
    io::print("Checking a: ")
    io::println(a)
    int num = a
    io::print("Checking num: ")
    io::println(num)
```

This prints out:

Checking a: NaN
Checking num: NaN

I think a compile error should occur at `int a = b * 2` as `b` is not assigned.

**Comment by DavePearce** [comment]
Hmmm, interesting.  Yes the order of evaluation for declarations is an interesting challenge.  Within a single file it can be determined, but across multiple files its much harder.

**Comment by DavePearce** [comment]
This is subsumed by #841
