### ISSUE TITLE
Multiple wheres in loop invariant isn't same as conjunction

### ISSUE THREAD

**Issue by SimonPope** [Whiley/WhileyCompiler#869]
There is not always a direct translation between using && to split up expressions in a loop invariant, and using multiple wheres. Below is an example from the test suite, which verifies fine as it is. However, if the line:

    where |c| == |a| && k <= |a|
is split into:

    where |c| == |a|
    where k <= |a|
it no longer verifies. It gives the error "loop invariant not restored" for *|c| == |a|*.

    type nat is (int x) where x >= 0
    
    property sum(int[] a, int[] b, int[] c, int n)
    where all { i in 0..n | c[i] == a[i] + b[i] }

    function arraySum2(int[] a, int[] b) -> (int[] c)
       requires |a| == |b|
       ensures |c| == |a|
       ensures sum(a,b,c,|a|):
          nat k = 0
          c = [0; |a|]
          while k < |a|
          where |c| == |a| && k <= |a|
          where sum(a,b,c,k):
              c[k] = a[k] + b[k]
              k = k + 1
          return c

**Comment by DavePearce** [comment]
Hi Simon,

This is probably a verifier bug / limitation of some kind.  Splitting the conjunct into multiple `where` clauses leads to more verification conditions being generated.

Still, it's a bit strange though.

**Comment by DavePearce** [comment]
This works fine with the new Boogie backend.
