### ISSUE TITLE
Potential infinite loop in toUnsignedInt() for ListAccess_Valid_8

### ISSUE THREAD

**Issue by JC626** [Whiley/WhileyCompiler#870]
For the valid test, `ListAccess_Valid_8` I think there could be potentially an infinite loop for larger byte values.

For example, we call with the decimal number 205 as a byte to the function `toUnsignedInt(11001101b)`. 
In Java, this is represented as a negative number, -51 as bytes in Java are between -128 and 128 or
11111111111111111111111111001101 in binary.

In the while loop, when we shift the `b = b >> 1` this will add a 1 to the left side and drop the number on the right side.

As a result, the while loop will eventually get stuck in an infinite loop as the binary number contains all 1's. 

This works correctly in WhileyLabs but not when I compile and run via the command line locally. 
Maybe this occurs because I am using an older version of the Interpreter?

**Comment by DavePearce** [comment]
Hmmm, perhaps it should be translated as an unsigned right shift then?  Hmmm.

**Comment by DavePearce** [comment]
This has been correct in various test cases now through the following:
```
        // NOTE: following mask needed in leu of unsigned right shift
        // operator.
        b = (b >> 1) & 0b01111111
```
This issue of non-termination also came up when I was implementing the `QuickCheck` command in Whiley.  There is now a related issue to add an unsigned shift operator #907.
