### ISSUE TITLE
Syntax/Type errors not reported for standalone source files

### ISSUE THREAD

**Issue by utting** [Whiley/WhileyCompiler#886]
When wyc.task.CompileTask.build(...) is used to compile a standalone Whiley source file (one that is not part of a project), for example via 'wy boogie' or 'wy compile', and it contains syntax or type errors, those errors are not reported.  Instead the user just sees an error:  "unknown unit".

The problem seems to be with this catch statement:

    public static void build(Logger logger, Project project, Entry<WyilFile> target, List<Entry<WhileyFile>> sources) throws IOException {
        try {
            ...
        } catch (SyntaxError var16) {
            SyntacticItem item = var16.getElement();
            if (var16.getEntry().contentType() == WyilFile.ContentType) {
                Unit unit = (Unit)item.getAncestor(Unit.class);
                Entry<WhileyFile> sf = getWhileySourceFile(unit.getName(), sources);
                throw new SyntaxError(var16.getMessage(), sf, item, var16.getCause());
            } else {
                throw var16;
            }
        }
    }

The getWhileySourceFile throws the "unknown unit" exception, which is reported instead of the original var16 SyntaxError exception.

It would be nice to drop back to throwing the original var16 exception instead, when this happens.

**Comment by DavePearce** [comment]
Hey Mark,

This was all a bit of a kludge to make it work.  I'm pretty sure it was reporting compilation errors for these files when I used it, so it feels like something wierd going on.

I'm actually in the process of making further updates the build process now, which requires a different approach to handling syntax errors anyway.  In particular, this will allow multiple errors for a given file and so won't use exceptions for this.  My plan is to update your module once I've completed this ... hopefully in the next week or so.

Anyhows, I'll try and have a look and see if there's an easy fix for this at some point.

**Comment by DavePearce** [comment]
**UPDATE:** actually, it might be helpful to know more about the source file your're compiling.  Is it, for example, in a `package`?

**Comment by utting** [comment]
Dave, 
The example where I noticed this was not in a package, it was just a standalone file (which contains a type error according to whileylabs.com).
That is: 
$ wy boogie length.whiley
java.lang.IllegalArgumentException: unknown unit
	at wyc.task.CompileTask.getWhileySourceFile(Unknown Source)
	at wyc.task.CompileTask.build(Unknown Source)
	at wy2boogie.commands.BoogieCommand.translateAnyWhileyFiles(BoogieCommand.java:161)
	at wy2boogie.commands.BoogieCommand.execute(BoogieCommand.java:128)
	at wycc.WyProject.execute(Unknown Source)
	at wycc.WyMain.execute(Unknown Source)
	at wycc.WyMain.main(Unknown Source)

[length.whiley.txt](https://github.com/Whiley/WhileyCompiler/files/2873560/length.whiley.txt)
