### ISSUE TITLE
Merge Template & Lifetime Parameters

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#944]
The distinction between declared lifetimes and type variables is a little frustrating.  The following from `Template_Valid_27` illustrates the issue:

```
method f<&a,T>(&a:int x, T y) -> (int r):
    //
    return *x
```

Here, the `&a` is declared the lifetime parameter `a` whilst `T` declared a type variable.  The distinction is present in the API as well, because `Binding.getArguments()` returns `Tuple<SyntacticItem>` rather than e.g. `Tuple<Type>`.

**Proposal**:  _merge lifetime and type declarations together._

This would mean the above is written:

```
method f<a,T>(&a:int x, T y) -> (int r):
    //
    return *x
```

Observe that using lowercase `a` versus upper case `T` is purely a convention to distinguish things intended to be lifetimes from things intended to be general types.  Of course, since `a` is no longer different in any sense from `T` then we can try to call e.g. `f<int,int>(...)` --- however, this would always fail binding.  In fact, _it would be impossible to bind a single variable as both a lifetime and a general type_.

However, there are a lot of details which might be affected by this proposal and need to be thought through.  For example, the issue of captured lifetimes immediately springs to mind.

**NOTE:** another advantage of this is that all the machinery would be in place for handling nominal types with declared lifetime (see #648).

**Comment by DavePearce** [comment]
@utting --- your thoughts on this would be welcome!

**Comment by utting** [comment]
This seems like a good idea, which could simplify the API a bit.
Dropping the explicit syntax flagging of lifetime parameters (with the &) maybe reduces readability very slightly for readers, but they can immediately see which role each parameter takes by scanning the rest of the signature to see how that variable is used. (And the lowercase/uppercase convention would preserve a syntactic distinction anyway).  

But if Binding.getArguments() returns Tuple<Type>, does this mean that lifetimes will be a subclass/subset of general types?  Presumably the order of these lifetime and type parameters is not semantically significant, so perhaps the API could separate them:  Binding.getTypeArguments() and Binding.getLifetimeArguments()?

**Comment by DavePearce** [comment]
> But if Binding.getArguments() returns Tuple, does this mean that lifetimes will be a subclass/subset of general types?

Yeah, that's right.  I'd propose to implement them using a `Type.Variable` instead of just an `Identifier`.  However, I'm not sure whether that would be sufficient or not ...

**Comment by DavePearce** [comment]
At this stage, my current plan now is actually to drop lifetimes altogether!  #1014
