### ISSUE TITLE
scanCharacterLiteral in FileLexer advances without checking length?

### ISSUE THREAD

**Issue by OlaFosheimGrostad** [Whiley/WhileyCompiler#987]
Is that right?

**Comment by DavePearce** [comment]
Hey,

Ok, looking at it ... yes I think you are right --- well spotted!!  Here's a failing input:

```
function f() -> int:
	 return '\
```

This results in the following exception:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 32
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
```

If you have time, feel free to put in a pull request for it.  I'm currently on holiday so not really doing much until after XMAS!

**Comment by OlaFosheimGrostad** [comment]
I haven't compiled Whiley yet, though. I was trying to translate the lexer to C++ and utf-8, but I think maybe it is easier to write a new lexer for utf8.

**Comment by OlaFosheimGrostad** [comment]
Actually, I think I've found a way to do utf8, just removing "Token.text" from non-string, non-name Tokens makes things easier and perhaps faster. Right now "from", "with" and "type" are missing Tokens.
